"use client";

import { useEffect, useMemo, useState } from "react";
import { Brain, Check, ChevronRight, Code2, Download, Flag, Flame, LockKeyhole, LogIn, Medal, MessageCircle, NotebookPen, Plus, Sparkles, Target, Trophy } from "lucide-react";
import { Progress } from "@/components/ui/progress";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";

type Mission = { id: string; title: string; detail: string; minutes: number; xp: number; kind: "confidence" | "discipline" };
type Goal = { id:string; title:string; why:string; days:number; startAt:string; progress:number; milestones:{title:string;day:number;done:boolean}[] };
type AppState = { xp: number; streak: number; completed: string[]; journal: { text: string; createdAt: string }[]; goals:Goal[] };
const missions: Mission[] = [
  { id: "courage", title: "Do the thing you’re avoiding", detail: "Choose one task you have delayed. Give it ten focused minutes—starting counts.", minutes: 10, xp: 40, kind: "discipline" },
  { id: "voice", title: "Speak to yourself like an ally", detail: "Write down one harsh thought, then replace it with something honest, useful and kind.", minutes: 5, xp: 25, kind: "confidence" },
  { id: "promise", title: "Keep one small promise", detail: "Pick a tiny commitment you can finish today. Complete it before adding another.", minutes: 15, xp: 35, kind: "discipline" },
  { id: "brave", title: "Take one brave action", detail: "Send the message, ask the question or share the idea you have been holding back.", minutes: 20, xp: 50, kind: "confidence" },
];
const defaults: AppState = { xp: 120, streak: 3, completed: [], journal: [], goals:[] };

export default function Home() {
  const [state, setState] = useState<AppState>(defaults);
  const [time, setTime] = useState(10);
  const [journal, setJournal] = useState("");
  const [coachOpen, setCoachOpen] = useState(false);
  const [coachText, setCoachText] = useState("");
  const [coachReply, setCoachReply] = useState("Tell me what feels hardest today. We’ll turn it into one doable next step.");
  const [goalOpen, setGoalOpen] = useState(false);
  const [goalTitle, setGoalTitle] = useState("");
  const [goalWhy, setGoalWhy] = useState("");
  const [goalDays, setGoalDays] = useState(30);
  const [user, setUser] = useState<{name:string;email:string}|null>(null);
  useEffect(() => { fetch("/api/me").then(r=>r.json()).then(d=>setUser(d.user)).catch(()=>{}); fetch("/api/state").then(r => r.ok ? r.json() : null).then(d => d?.state && setState(d.state)).catch(() => {}); }, []);
  const save = async (next: AppState) => { setState(next); await fetch("/api/state", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(next) }).catch(() => {}); };
  const available = useMemo(() => missions.filter(m => m.minutes <= Math.max(time, 5)), [time]);
  const level = Math.floor(state.xp / 200) + 1;
  const levelProgress = state.xp % 200;
  const complete = (mission: Mission) => { if (!state.completed.includes(mission.id)) void save({ ...state, xp: state.xp + mission.xp, completed: [...state.completed, mission.id] }); };
  const addJournal = () => { if (journal.trim()) { void save({ ...state, journal: [{ text: journal.trim(), createdAt: new Date().toISOString() }, ...state.journal] }); setJournal(""); } };
  const askCoach = () => { const t = coachText.toLowerCase(); setCoachReply(t.includes("confidence") || t.includes("nervous") ? "Confidence comes after evidence. Pick the smallest brave action you can finish in ten minutes, then let that win count." : t.includes("motivat") || t.includes("discipline") ? "Don’t wait to feel ready. Shrink the task until starting feels almost too easy, then do five focused minutes." : "Let’s make this concrete: name the one action that would make today feel like progress, then reduce it to a ten-minute first move."); setCoachText(""); };
  const addGoal = (preset?:string) => {
    const title=(preset||goalTitle).trim(); if(!title)return;
    const steps=[{title:"Define exactly what success looks like",day:1,done:false},{title:"Build the weekly routine",day:Math.max(3,Math.round(goalDays*.15)),done:false},{title:"Prove consistency for two weeks",day:Math.max(14,Math.round(goalDays*.45)),done:false},{title:"Review, adjust and raise the standard",day:Math.max(21,Math.round(goalDays*.72)),done:false},{title:"Complete the goal and lock in the habit",day:goalDays,done:false}];
    const goal:Goal={id:crypto.randomUUID(),title,why:goalWhy||"Become someone who follows through.",days:goalDays,startAt:new Date().toISOString(),progress:0,milestones:steps};
    void save({...state,goals:[goal,...state.goals]}); setGoalTitle("");setGoalWhy("");setGoalOpen(false);
  };
  const toggleMilestone=(goalId:string,index:number)=>{const goals=state.goals.map(g=>{if(g.id!==goalId)return g;const milestones=g.milestones.map((m,i)=>i===index?{...m,done:!m.done}:m);return {...g,milestones,progress:Math.round(milestones.filter(m=>m.done).length/milestones.length*100)};});void save({...state,goals});};
  const activeGoal=state.goals[0];
  useEffect(() => {
    const context = (document as Document & { modelContext?: { registerTool: (tool: unknown, options?: { signal?: AbortSignal }) => void | Promise<void> } }).modelContext;
    if (!context?.registerTool) return;
    const lifecycle = new AbortController();
    void Promise.resolve(context.registerTool({ name:"complete_mission", title:"Complete mission", description:"Mark one of today's confidence or discipline missions complete and award its XP.", inputSchema:{type:"object",properties:{missionId:{type:"string",enum:missions.map(m=>m.id)}},required:["missionId"],additionalProperties:false}, annotations:{readOnlyHint:false,untrustedContentHint:false}, execute:(input:unknown)=>{const id=(input as {missionId?:string}).missionId; const mission=missions.find(m=>m.id===id); if(!mission) throw new Error("Unknown mission"); complete(mission); return {completed:mission.id,xpAwarded:mission.xp};} },{signal:lifecycle.signal}));
    void Promise.resolve(context.registerTool({ name:"save_reflection", title:"Save reflection", description:"Save a private journal reflection in the visible app.", inputSchema:{type:"object",properties:{text:{type:"string",minLength:1,maxLength:2000}},required:["text"],additionalProperties:false}, annotations:{readOnlyHint:false,untrustedContentHint:true}, execute:(input:unknown)=>{const text=(input as {text?:string}).text?.trim(); if(!text) throw new Error("Reflection is required"); void save({...state,journal:[{text,createdAt:new Date().toISOString()},...state.journal]}); return {saved:true};} },{signal:lifecycle.signal}));
    return () => lifecycle.abort();
  }, [state]);

  return <main className="min-h-screen bg-[#071016] text-[#f4f7f8]"><div className="mx-auto max-w-6xl px-4 pb-28 pt-5 sm:px-7 sm:pt-8">
    <header className="mb-8 flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><div className="brand-mark">B</div><div><p className="text-lg font-black tracking-[-.03em]">BECOME</p><p className="text-xs text-slate-400">Build proof. Become stronger.</p></div></div><div className="flex flex-wrap items-center gap-2"><a href="https://github.com/northloopme-create/become-life-coach" target="_blank" rel="noreferrer" className="header-action"><Code2/>Source</a><a href="https://github.com/northloopme-create/become-life-coach/releases/latest/download/become.apk" className="header-action"><Download/>APK</a>{user?<div className="flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-3 py-2 text-sm"><Flame className="h-4 w-4 text-orange-400"/><b>{state.streak}</b><span className="hidden text-slate-400 sm:inline">day streak</span></div>:<a href="/signin-with-chatgpt?return_to=%2F" target="_top" className="signin-button"><LogIn/>Sign in</a>}</div></header>
    {!user&&<div className="signin-banner"><div><b>Sign in to save your journey</b><p>Your goals, journal and progress stay securely linked to your account.</p></div><a href="/signin-with-chatgpt?return_to=%2F" target="_top">Sign in with ChatGPT</a></div>}
    <section className="grid gap-6 lg:grid-cols-[1.45fr_.75fr]"><div>
      <div className="mb-5 flex items-end justify-between gap-4"><div><p className="eyebrow">TODAY · DAY {state.streak + 1}</p><h1 className="mt-2 max-w-xl text-4xl font-black leading-[.98] tracking-[-.055em] sm:text-6xl">Small actions.<br/><span className="text-[#57e6b1]">Real momentum.</span></h1></div><Sparkles className="mb-2 hidden h-12 w-12 text-[#a878ff] sm:block"/></div>
      <div className="time-card"><div><p className="font-bold">How much have you got today?</p><p className="mt-1 text-sm text-slate-400">Your missions adapt—no guilt, no falling behind.</p></div><div className="mt-4 flex flex-wrap gap-2 sm:mt-0">{[5,10,20,30].map(v => <button key={v} onClick={() => setTime(v)} className={time === v ? "time-pill active" : "time-pill"}>{v} min</button>)}</div></div>
      <section className="reach-card"><div className="reach-top"><div><p className="eyebrow">DAILY REACH</p><h2 className="mt-2 text-2xl font-black">{activeGoal ? `Move “${activeGoal.title}” forward` : "Set the direction—then take one step"}</h2><p className="mt-2 max-w-xl text-sm leading-6 text-slate-300">{activeGoal ? `Today’s win: spend ${Math.max(5,time)} focused minutes on the next milestone. You don’t need to finish it—you only need evidence that you moved.` : "Choose one meaningful goal. Become will turn it into a timeline, milestones and a realistic daily action."}</p></div><div className="reach-ring"><span>{activeGoal?.progress||0}%</span></div></div><div className="mt-4 flex flex-wrap items-center gap-3"><Dialog open={goalOpen} onOpenChange={setGoalOpen}><DialogTrigger asChild><button className="primary-button flex items-center gap-2"><Plus className="h-4 w-4"/>{activeGoal?"Add another goal":"Create my first goal"}</button></DialogTrigger><DialogContent className="border-white/10 bg-[#101b23] text-white sm:max-w-xl"><DialogHeader><DialogTitle>Build an achievable goal</DialogTitle></DialogHeader><div><label className="field-label">What do you want to achieve?</label><input value={goalTitle} onChange={e=>setGoalTitle(e.target.value)} placeholder="e.g. Become confident speaking in meetings" className="goal-input"/></div><div><label className="field-label">Why does it matter?</label><input value={goalWhy} onChange={e=>setGoalWhy(e.target.value)} placeholder="The reason you want to keep going" className="goal-input"/></div><div><label className="field-label">Choose a realistic timeline</label><div className="mt-2 grid grid-cols-3 gap-2">{[30,90,180].map(d=><button key={d} onClick={()=>setGoalDays(d)} className={goalDays===d?"duration active":"duration"}>{d===30?"30 days":d===90?"90 days":"6 months"}</button>)}</div></div><button onClick={()=>addGoal()} className="primary-button">Create goal timeline</button></DialogContent></Dialog><span className="text-sm text-slate-400">Aim high. Build small. Repeat.</span></div></section>
      <div className="mt-6 flex items-center justify-between"><h2 className="text-xl font-extrabold">Your missions</h2><span className="text-sm text-slate-400">{state.completed.length}/{missions.length} complete</span></div>
      <div className="mt-3 grid gap-3 sm:grid-cols-2">{available.map((m, i) => { const done = state.completed.includes(m.id); return <article key={m.id} className={`mission-card ${done ? "done" : ""}`}><div className="flex items-start justify-between"><span className={`mission-icon ${m.kind}`}>{done ? <Check/> : m.kind === "confidence" ? <Brain/> : <Target/>}</span><span className="xp">+{m.xp} XP</span></div><div className="mt-5"><p className="text-xs font-bold uppercase tracking-widest text-slate-400">Mission {i + 1} · {m.minutes} min</p><h3 className="mt-2 text-xl font-extrabold leading-tight">{m.title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{m.detail}</p></div><button onClick={() => complete(m)} disabled={done} className="mission-button">{done ? "Completed" : "Mark complete"}<ChevronRight className="h-4 w-4"/></button></article>})}</div>
    </div><aside className="space-y-4">
      <section className="goal-card"><div className="flex items-center justify-between"><div><p className="eyebrow">GOAL TIMELINE</p><h2 className="mt-2 text-xl font-black">{activeGoal?.title||"Choose your next target"}</h2></div><Flag className="h-7 w-7 text-[#a878ff]"/></div>{activeGoal?<><div className="mt-4 flex items-center justify-between text-sm"><span className="text-slate-400">{activeGoal.days} day plan</span><b>{activeGoal.progress}% complete</b></div><Progress value={activeGoal.progress} className="mt-2 h-2 bg-white/10 [&>div]:bg-[#a878ff]"/><div className="timeline">{activeGoal.milestones.map((m,i)=><button key={m.title} onClick={()=>toggleMilestone(activeGoal.id,i)} className={m.done?"timeline-step done":"timeline-step"}><span className="timeline-dot">{m.done?<Check/>:i+1}</span><span><b>{m.title}</b><small>By day {m.day}</small></span></button>)}</div></>:<><p className="mt-3 text-sm leading-6 text-slate-400">Start with one of these, or create your own:</p><div className="mt-3 grid gap-2">{["Build unshakeable confidence","Create a disciplined morning routine","Improve my fitness and energy","Reach my next career milestone"].map(g=><button key={g} onClick={()=>addGoal(g)} className="preset-goal"><Trophy className="h-4 w-4"/>{g}<ChevronRight className="ml-auto h-4 w-4"/></button>)}</div></>}</section>
      <section className="level-card"><div className="flex items-center justify-between"><div><p className="eyebrow">YOUR PROGRESS</p><h2 className="mt-2 text-2xl font-black">Level {level} · Builder</h2></div><Medal className="h-9 w-9 text-[#ffca69]"/></div><div className="mt-7 flex items-baseline justify-between"><span className="text-3xl font-black">{state.xp} XP</span><span className="text-sm text-slate-400">{200-levelProgress} to Level {level+1}</span></div><Progress value={levelProgress/2} className="mt-3 h-2 bg-white/10 [&>div]:bg-[#57e6b1]"/><div className="mt-6 grid grid-cols-3 gap-2 text-center"><Stat value={state.streak} label="streak"/><Stat value={state.completed.length} label="wins"/><Stat value={state.journal.length} label="notes"/></div></section>
      <Dialog open={coachOpen} onOpenChange={setCoachOpen}><DialogTrigger asChild><button className="coach-card"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#a878ff] text-[#120b1e]"><MessageCircle/></span><span className="text-left"><b className="block text-lg">Talk to your coach</b><span className="text-sm text-slate-400">Get one clear next step</span></span><ChevronRight className="ml-auto"/></button></DialogTrigger><DialogContent className="border-white/10 bg-[#101b23] text-white sm:max-w-lg"><DialogHeader><DialogTitle>Your coach</DialogTitle></DialogHeader><div className="coach-bubble">{coachReply}</div><Textarea value={coachText} onChange={e=>setCoachText(e.target.value)} placeholder="What’s on your mind?" className="min-h-28 border-white/10 bg-black/20"/><button onClick={askCoach} className="primary-button">Get my next step</button></DialogContent></Dialog>
      <section className="journal-card"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><NotebookPen className="h-5 w-5 text-[#57e6b1]"/><h2 className="font-extrabold">Private journal</h2></div><LockKeyhole className="h-4 w-4 text-slate-500"/></div><p className="mt-3 text-sm text-slate-400">What did you prove to yourself today?</p><Textarea value={journal} onChange={e=>setJournal(e.target.value)} placeholder="I showed up by…" className="mt-3 min-h-24 border-white/10 bg-black/20"/><button onClick={addJournal} className="mt-3 w-full rounded-xl bg-white px-4 py-3 font-bold text-[#071016]">Save reflection</button></section>
    </aside></section>
    <Tabs defaultValue="today" className="fixed inset-x-0 bottom-0 z-20 mx-auto max-w-md px-3 pb-3"><TabsList className="h-auto w-full rounded-2xl border border-white/10 bg-[#111d24]/95 p-1.5 shadow-2xl backdrop-blur"><TabsTrigger value="today" className="flex-1 rounded-xl py-3 data-[state=active]:bg-[#57e6b1] data-[state=active]:text-[#071016]">Today</TabsTrigger><TabsTrigger value="progress" className="flex-1 rounded-xl py-3" onClick={()=>document.querySelector('.level-card')?.scrollIntoView({behavior:'smooth'})}>Progress</TabsTrigger><TabsTrigger value="journal" className="flex-1 rounded-xl py-3" onClick={()=>document.querySelector('.journal-card')?.scrollIntoView({behavior:'smooth'})}>Journal</TabsTrigger></TabsList><TabsContent value="today"/><TabsContent value="progress"/><TabsContent value="journal"/></Tabs>
  </div></main>;
}
function Stat({value,label}:{value:number;label:string}) { return <div className="rounded-xl bg-black/20 px-2 py-3"><b className="block text-xl">{value}</b><span className="text-xs text-slate-400">{label}</span></div> }
